### ISSUE TITLE
hw93 feedback

### ISSUE THREAD

**Issue by DavidHolmes0** [JonasLopez/Hedgemony#2]
Looks good.

## recursive abstraction
This looks close. But the language about "one legal move closer to treasure" seems misguided, since when your program is ready to invoke the recursive abstraction, it has no way to know which direction satisfies that.

**Comment by JonasLopez** [comment]
We fixed the issue in the recursive abstraction by mentioning adjacent spaces instead of one legal move closer to treasure so that it could work without knowing which direction satisfies it.
